#!/usr/bin/env bash
# Regenerate docs/AxiomAudit.md: run Lean's `#print axioms` on every key declaration and
# archive the result. Run after `lake build`. Usage: scripts/audit.sh
set -u
cd "$(dirname "$0")/.." || exit 2

decls=(
  # Main body (Etter, Three-place Identity) — the headline theorem
  UniversalityTheorem.slang_universality_ZFC
  # Appendix B: Etter's cell construction (The Expressive Power of Equality)
  UniversalityTheorem.Cell.equiv_R
  UniversalityTheorem.Cell.equiv_C
  UniversalityTheorem.Cell.equiv_V
  UniversalityTheorem.Cell.cell_identity
  UniversalityTheorem.Cell.rcv_identity
  UniversalityTheorem.Cell.first_iff
  UniversalityTheorem.Cell.mem_iff
  UniversalityTheorem.Cell.val_surjective
  UniversalityTheorem.Cell.mem_iff_zf
  UniversalityTheorem.Cell.mem_irreflexive
  UniversalityTheorem.Cell.mem_asymmetric
  UniversalityTheorem.Cell.mem_not_symmetric
  # RCV-language interface over the cell construction
  UniversalityTheorem.RCV.mem_RCV_iff_zf
  UniversalityTheorem.RCV.mem_RCV_definable
  UniversalityTheorem.RCV.first_RCV_definable
  UniversalityTheorem.RCV.mem_RCV_irreflexive
  UniversalityTheorem.RCV.mem_RCV_asymmetric
  # Appendix A: kept irreflexivity + the proof that the naive intersection candidate fails
  UniversalityTheorem.Stereo.stereo_irreflexivity
  UniversalityTheorem.Stereo.intersectionMem_symm
  UniversalityTheorem.Stereo.symm_mem_no_empty_member
  UniversalityTheorem.Stereo.intersectionMem_not_ZF
  # The one genuinely open item: a stated conjecture (a Prop), not a proved theorem
  UniversalityTheorem.Stereo.etterStereoConjecture
)

src=/tmp/lean_audit.lean
: > "$src"
echo 'import UniversalityTheorem' >> "$src"
echo 'import UniversalityTheorem.Cell' >> "$src"
for d in "${decls[@]}"; do echo "#print axioms $d" >> "$src"; done

out=docs/AxiomAudit.md
{
  echo "# Axiom audit"
  echo
  echo "Generated by \`scripts/audit.sh\` using Lean's \`#print axioms\`. Every key result"
  echo "should depend only on \`propext\` / \`Quot.sound\` (the latter from \`ZFSet\`'s quotient"
  echo "construction). The project is \`sorry\`-free: **no** declaration depends on \`sorryAx\`."
  echo "The two-equality Stereo result is not a proved theorem but a stated *conjecture*,"
  echo "\`etterStereoConjecture\` (a \`Prop\`; see \`Errata.pdf\` Erratum 3 and \`ROADMAP.md\`"
  echo "Phase 4) — listed below only to confirm it is a well-formed, axiom-clean proposition."
  echo
  echo '```'
  lake env lean "$src" 2>&1 | grep -vE 'LEAN_PATH|^trace:'
  echo '```'
} > "$out"
echo "wrote $out"
